#!/usr/bin/python

import sys, os
#sys.path.insert(0, "../src")
from rdiff_backup.rpath import *
from rdiff_backup.connection import *
from rdiff_backup import Globals

lc = Globals.local_connection

for filename in sys.argv[1:]:
	#print "Deleting %s" % filename
	rp = RPath(lc, filename)
	if rp.lstat(): rp.delete()
	#os.system("rm -rf " + rp.path)
