#!/usr/bin/env python

"""Used to emulate a remote connection by changing directories.

Like chdir-wrapper, but this time run the 'rdiff-backup' script, not
some other special thing.

"""

import os, sys

if len(sys.argv) > 1:
	olddir = os.getcwd()
	os.chdir(sys.argv[1])
#PipeConnection(sys.stdin, sys.stdout).Server()

os.system(os.path.join(olddir, "../rdiff-backup") + " --server")

