= Windows development environment (on Linux)
:sectnums:
:toc:

== Installation steps

=== under Ubuntu

First install Vagrant:

.Follow https://developer.hashicorp.com/vagrant/install
[source,shell]
----
wget -O - https://apt.releases.hashicorp.com/gpg | \
	sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(grep -oP '(?<=UBUNTU_CODENAME=).*' /etc/os-release || lsb_release -cs) main" | \
	sudo tee /etc/apt/sources.list.d/hashicorp.list
sudo apt update && sudo apt install vagrant
----

.Then continue with
[source,shell]
----
sudo apt install libvirt-dev virt-manager  # virt-manager is possibly too much but works!
sudo apt install ansible-core ansible-  # you can install the full ansible, I prefer not
sudo systemctl start libvirtd
----

=== Under Fedora

The trick so far to make vagrant work under Fedora is to install vagrant from repository but _no_ vagrant plugin:

----
sudo dnf install vagrant ruby-devel libvirt-devel
----

IMPORTANT: Make sure no vagrant plugin is installed as RPM.

=== Further steps

I personally want to run vagrant as normal user so make yourself part of the libvirt group:
`sudo usermod --append -G libvirt myuser` (tested under Ubuntu) or add something like the following polkit rule (under Fedora):

.`/etc/polkit-1/rules.d/80-vagrant-libvirt.rules`
----
polkit.addRule(function(action, subject) {
  if (action.id == "org.libvirt.unix.manage" && subject.local && subject.active && subject.isInGroup("wheel")) {
      return polkit.Result.YES;
  }
});
----

In both cases, it's best to reboot.

== Configure vagrant and create the VM

After that you can run:

[source,shell]
----
ansible-galaxy collection install -r collections/requirements.yml  # or 216 for ansible 2.16
vagrant plugin install vagrant-libvirt winrm winrm-elevated
vagrant up
vagrant provision  # if the provisioning fails before
vagrant reload  # just to be sure Windows is ready "reboot tut gut"
ansible -m win_ping winbuilder  # make sure Ansible is properly configured
----

=== If you already have a development Windows

If you already have a Windows VM/PC/laptop/server, you'd like to use for rdiff-backup development, you don't need to use Vagrant, you can directly use Ansible:

. Make your https://docs.ansible.com/ansible/latest/user_guide/windows_setup.html[Windows host ready for Ansible].
. Create an inventory that looks as after this list.
. Call directly the provisioning playbook `ansible-playbook -i YOURINVENTORYFILE playbook-provision-windows.yml`.

Your inventory should look as follows, depending on your exact Windows setup, replacing at least the `MY*` placeholders (some level of Ansible knowledge doesn't hurt here):

[source, ini]
----
[windows_ansible]
MYWINDOWSHOST ansible_host=192.168.1.MYIP ansible_user='MYUSER' ansible_password='MYPASSWORD'

[windows_ansible:vars]
ansible_connection=winrm
ansible_port=5986
ansible_winrm_server_cert_validation=ignore
----

== Build, test, debug

It can be as easy as calling ansible-playbook:

[source, shell]
----
ansible-playbook playbook-pipeline.yml  # build librsync and rdiff-backup
ansible-playbook playbook-pipeline.yml -e rdiff_version_tag=mybranch  # same thing with branch
ansible-playbook playbook-test-rdiff-backup.yml  # unpack test files and test
ansible-playbook playbook-debug-rdiff-backup.yml  # prepare venv and script for debugging
----

Then open a console e.g. using `vagrant ssh` and here you go:

[source, shell]
----
cd %HOME%\Develop\rdiff-backup
git checkout mybranch  # if not already done
.\dist\setup-rdiff-backup.bat  # join the virtual environment
pip install .  # each time you do code changes
rdiff-backup --version
rdiff-backup sourcedir targetdir
python -m pdb -m rdiffbackup.run sourcedir targetdir
[...]
deactivate  # leave the virtual environment
----

If you do changes to the source code, you can rebuild using the playbook(s) and try again.

NOTE: If you do changes outside of the VM, you'll need to do `git pull` on your own, the playbooks doesn't (yet) take care of it for you.

Testing goes with:

----
SET LIBRSYNC_DIR=C:\Users\vagrant\librsync64
tox -c tox_win.ini
----

== Samba server

If you need a samba server to do some specific tests, you can simply call explicitly `vagrant up samba`, followed by something like `vagrant ssh samba` to log onto the machine.

There are 2 shares available, one `\\samba\readonlyshare` and one `\\samba\readwriteshare`, (the difference should be obvious), which you can map on the Windows VM using a command like `net use x: \\samba\whichevershare` (or use directly).

== Miscellaneous considerations (possibly outdated)

=== Vagrant and Ansible

Vagrant manages an inventory file for Ansible, so that commands like the following ones are possible:

----
ansible -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory -m win_reboot default
ansible-playbook -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory playbook-provision-windows.yml -vvvvv
----

=== Libvirt

After the installation of the virtio drivers, shutdown the VM and go to the virtmanager and change following parameters to get more performance:

* OS information \-> Operating System \-> Microsoft Windows 10

Those two settings were overwritten at next `vagrant up` and led to some issues:

* Video _whatever_ \-> Model: Virtio, 3D acceleration: set
* Display VNC \-> Type: Spice server, Listen type: none and OpenGL: set

Those two settings didn't work as expected and made boot resp.
network fail:

* SATA Disk 1 \-> Advanced options \-> Disk bus: VirtIO
* NIC _whatever_ \-> Device model: virtio

=== Chocolatey

The logs of Chocolatey are available under `C:\ProgramData\chocolatey\logs` and `C:\Users\IEUser\AppData\Local\Temp\chcolatey`.

At some point in time, the VS Code packaging for the VC workload was broken and the only solution was to call _as administrator_ from the command line in the Windows VM `C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe" modify --installPath "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools" --includeRecommended --norestart --quiet --add Microsoft.VisualStudio.Workload.VCTools`.

=== Cygwin

You can install new Cygwin packages using `cyg-get.bat`, e.g.
`cyg-get vim` or `cyg-get /?` (`cyg-get --help` isn't foreseen but seems to give much more parameters).

You can start Cygwin using `\tools\cygwin\Cygwin.bat`.
