# Site settings
title: Rdiff-backup
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  rdiff-backup backs up one directory to another, possibly over a network. The target directory ends up a copy of the source directory, but extra reverse diffs are stored in a special subdirectory of that target directory, so you can still recover files lost some time ago. The idea is to combine the best features of a mirror and an incremental backup. rdiff-backup also preserves subdirectories, hard links, dev files, permissions, uid/gid ownership (if it is running as root), modification times, acls, eas, resource forks, etc. Finally, rdiff-backup can operate in a bandwidth efficient manner over a pipe, like rsync. Thus you can use rdiff-backup and ssh to securely back a hard drive up to a remote location, and only the differences will be transmitted.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rdiff-backup.org" # the base hostname & protocol for your site
github_username:  sol1

# Build settings
markdown: kramdown
