# Site settings
title: Rdiff-backup
#email: your-email@domain.com
description: Reverse differential backup tool, over a network or locally.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rdiff-backup.org" # the base hostname & protocol for your site
github_username: sol1

# Build settings
markdown: kramdown
