#! /usr/bin/python

# Generate a series of (OFFSET,LENGTH) pairs for testing map_ptr, and
# also the output file that ought to be generated by them.  In this
# variant, we generate reads which run past the end of the file, and
# therefore test EOF handling.

# Copyright (C) 2000 by Martin Pool
# $Id$

import sys
from random import randint

ntests = 2000

suck = open(sys.argv[3]).read()
filelen = len(suck)

cmdfile = open(sys.argv[1], 'wt')
datafile = open(sys.argv[2], 'wb')

for i in range(ntests):
    off = randint(0, filelen - 1)
    amount = randint(1, filelen * 2)

    cmdfile.write('%d,%d ' % (off,amount))
    # Python doesn't care about us indexing past the end of the array
    datafile.write(suck[off:off+amount])
