#!/usr/bin/env python

"""Used to emulate a remote connection by changing directories.

If given an argument, will change to that directory, and then start
the server.  Otherwise will start the server without a chdir.

"""

import os, sys

#execfile("commontest.py")
#rbexec("setconnections.py")

if len(sys.argv) > 1: os.chdir(sys.argv[1])
#PipeConnection(sys.stdin, sys.stdout).Server()

os.system("/home/ben/prog/python/rdiff-backup/src/rdiff-backup --server")
