#!/usr/bin/python

import sys, os

curdir = os.getcwd()
os.chdir("../src")
execfile("selection.py")
os.chdir(curdir)

lc = Globals.local_connection

for filename in sys.argv[1:]:
	#print "Deleting %s" % filename
	rp = RPath(lc, filename)
	if rp.lstat(): rp.delete()
	#os.system("rm -rf " + rp.path)
