#!/bin/sh

# This script will create the testing/restoretest3 directory as it
# needs to be for one of the tests in restoretest.py to work.

rm -rvf ${PWD}_testfiles/restoretest3
for i in 1 2 3 4
do
	rdiff-backup -v5 --current-time $((i * 10000)) ${PWD}_testfiles/increment${i} ${PWD}_testfiles/restoretest3
done
