---
galaxy_info:
  author: Bert Van Vreckem
  description: >-
    Ansible role for basic setup of a server with a RedHat-based Linux
    distribution (CentOS, Fedora, RHEL, ...) with the systemd init system.
  license: BSD
  min_ansible_version: 2.1
  platforms:
    - name: EL
      versions:
        - 7
    - name: Fedora
      versions:
        - 29
  galaxy_tags:
    - system
dependencies: []
