= image:../resources/logo-banner.svg[rdiff-backup] rdiff-backup: Duplicity
:sectnums:

Reverse differential backup tool, over a network or locally

[[pages]]
xref:../index.adoc[Home] xref:./features.adoc[Features]
xref:./docs.adoc[Documentation]
xref:./acknowledgments.adoc[Acknowledgement] xref:./related.adoc[Related
pages]

'''''

Duplicity is a backup program that is similar to rdiff-backup in some
ways. It grew out of rdiff-backup, is also written in Python, and uses
librsync for bandwidth efficiency. However, rdiff-backup's archives are
meant to be as easy to view as possible, while duplicity's are as hard
to view as possible---they can be encrypted with GnuPG. Also, duplicity
saves data in the more conventional full+forward delta format instead of
rdiff-backup's mirror+reverse deltas. Finally, rdiff-backup another copy
of rdiff-backup on the remote destination, while duplicity can access
remote locations with scp or ftp (other backends may be supported
later).

For more information, see the
*http://www.nongnu.org/duplicity/[duplicity page]*.
