# "It took the night to believe"

language: c

before_script:
  - cmake --help
  - cmake $CMAKE_OPTIONS $CMAKE_GENERATOR .
  
sudo: required

env:
  - CTEST_OUTPUT_ON_FAILURE=1

addons:
  apt:
    packages:
    - cmake
    - libpopt-dev
    - doxygen
    - ninja-build

script:
  - make check

matrix:
  include:
    - compiler: clang
      os: osx
      before_install:
        - brew update
        - brew install popt
      script:
        - make check doc

    - dist: xenial
      sudo: false

    - compiler: clang
      dist: xenial

    - compiler: clang
      env: CMAKE_GENERATOR="-G Ninja"
      dist: xenial
      script:
        - ninja check doc

    - dist: xenial
      sudo: false
      env: CMAKE_OPTIONS="-D BUILD_RDIFF=OFF"


# All tests are on xenial and OSX (which probably has older versions of
# everything).

# vim: shiftwidth=2 expandtab
