#!/usr/bin/python

import sys, os
sys.path.insert(0, "../rdiff_backup")
from rpath import *
from connection import *
import Globals

lc = Globals.local_connection

for filename in sys.argv[1:]:
	#print "Deleting %s" % filename
	rp = RPath(lc, filename)
	if rp.lstat(): rp.delete()
	#os.system("rm -rf " + rp.path)
