:sectnums:
:toc:

*NOTE!* This list is not complete.
Please also see the git log itself for authors and committers and the Github statistics at:

* https://github.com/rdiff-backup/rdiff-backup/people
* https://github.com/rdiff-backup/rdiff-backup/graphs/contributors

Project Lead / Maintainer History:

* From August 2019 onwards the main driver for the project is Eric L.
supported by Seravo.
* Sol1 has officially taken over stewardship of rdiff-backup from February 2016.
* Edward Ned Harvey, maintainer 2012 to 2016
* Andrew Ferguson, maintainer 2008 to 2012
* Dean Gaudet, maintainer 2006 to 2007
* Ben Escoto, original author, maintainer 2001 to 2005.

Other code contributors are:

* Daniel Hazelbaker, who contributed Mac OS X resource fork support.
(July 2003)
* Dean Gaudet, for checking in many patches, and for finding and fixing many bugs.
* Andrew Ferguson, for improving Mac OS X support and fixing many user-reported bugs.
* Josh Nisly, for contributing native Windows support.
(June 2008)
* Fred Gansevles, for contributing Windows ACLs support.
(July 2008)

Thanks also to:

* The http://www.fsf.org/[Free Software Foundation], for previously hosting the rdiff-backup project via their Savannah system.
* Andrew Tridgell and Martin Pool for writing rdiff, and also for rsync, which gave Ben Escoto the idea.
* Martin Pool and Donovan Baarda for their work on librsync, which rdiff-backup needs.
* Michael Friedlander for initially acting interested in the idea and giving me accounts for testing.
* Lots of people on the mailing list for their helpful comments, advice, and patches, particularly Alberto Accomazzi, Donovan Baarda, Jeb Campbell, Greg Freemyer, Jamie Heilman, Marc Dyksterhouse, and Ralph Lehmann.
