= rdiff-backup: {page-name}
:page-name: Main Page
:sectnums:
:toc: macro

_// Reverse differential backup tool, over a network or locally

'''''

toc::[]

== Introduction

Rdiff-backup backs up one directory to another, possibly over a network.
The target directory ends up a copy of the source directory, but extra reverse diffs are stored in a special subdirectory of that target directory, so you can still recover files lost some time ago.
The idea is to combine the best features of a mirror and an incremental backup.
Rdiff-backup also preserves subdirectories, hard links, dev files, permissions, uid/gid ownership (if it is running as root), modification times, acls, eas, resource forks, etc.
Finally, rdiff-backup can operate in a bandwidth efficient manner over a pipe, like rsync.
Thus you can use rdiff-backup and ssh to securely back a hard drive up to a remote location, and only the differences will be transmitted.

== Documentation

=== User documentation

* Installation instructions are directly available from our https://github.com/rdiff-backup/rdiff-backup#1-installation[GitHub site], from https://github.com/rdiff-backup/rdiff-backup/releases[which] you can also download the binaries (if not already packaged for your preferred distro).
* xref:features.adoc[Most relevant features]
* xref:examples.adoc[Usage examples]
* xref:FAQ.adoc[Frequently asked questions]
* xref:Windows-README.adoc[Windows specific documentation] - possibly outdated
* xref:migration.adoc[How to migrate from rdiff-backup 1.x to 2.x]
* man pages (_no navigation, come back with your browser's keys_):
** xref:rdiff-backup.1.adoc[rdiff-backup(1)]
** xref:rdiff-backup-delete.1.adoc[rdiff-backup-delete(1)]
** xref:rdiff-backup-statistics.1.adoc[rdiff-backup-statistics(1)]
** link:other/rdiff-backup-old.1.html[rdiff-backup-old(1)^] (generated with man2html)
* http://arctic.org/~dean/rdiff-backup/unattended.html[Dean Gaudet's unattended rdiff-backup page^] details how to configure ssh to make unattended rdiff-backup sessions more secure.

=== Developer documentation

* xref:DEVELOP.adoc[Developer documentation]
** xref:Windows-DEVELOP.adoc[Windows specific Developer documentation]
* xref:CODING.adoc[Coding conventions]
* xref:DOCUMENTATION.adoc[Documentation guidelines]
* link:./api[Client-server API documentation] (i.e. when used over SSH)
* link:./arch[Architecture documentation], if you want/need to know the internals of rdiff-backup
* http://www.w3.org/TR/NOTE-datetime[W3 note describing a time format rdiff-backup uses^]

=== Other documentation

* xref:credits.adoc[Authors and credits]
* xref:other/related.adoc[related topics and projects]

== Support or Contact

If you have everything installed properly, and it still doesn't work, see the enclosed xref:FAQ.adoc[FAQ], the https://rdiff-backup.net/[rdiff-backup web page^] (if you're not yet on it) and/or the https://lists.nongnu.org/mailman/listinfo/rdiff-backup-users[rdiff-backup-users mailing list^].

We're also happy to help if you create an issue to our https://github.com/rdiff-backup/rdiff-backup/issues[GitHub repo^].

The most important is probably to explain what happened with which version of rdiff-backup, with which command parameters on which operating system version, and attach the output of rdiff-backup run with the very verbose option `-v9`.

This is an open source project and contributions are welcome!

== History

Rdiff-backup has been around for almost 20 years now and has proved to be a very solid solution for backups and it is still unique in its model of unlimited incrementals with no need to space consuming regular full backups.

Current lead developers are Eric Lavarde, Patrik Dufresne and Otto Kek채l채inen.
For other members check the xref:credits.adoc[credits page].

The original author and maintainer was *Ben Escoto* from 2001 to 2005.
Key contributors from 2005 to 2016 were Dean Gaudet, Andrew Ferguson and Edward Ned Harvey.
After some hibernation time Sol1 took over the stewardship of rdiff-backup from February 2016 but there were no new releases.
In August 2019 https://eric.lavar.de/[Eric Lavarde^] with the support of Otto Kek채l채inen from https://seravo.com/[Seravo^] and Patrik Dufresne from http://minarca.org/[Minarca^] took over, completed the Python 3 rewrite and finally released rdiff-backup 2.0 in March 2020.
