#!/usr/bin/env python3
# rdiff-backup -- Mirror files while keeping incremental changes
# Copyright (C) 2001-2005  Ben Escoto <rdiff-backup@emerose.org>
#
# This program is licensed under the GNU General Public License (GPL).
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation,
# Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA; either
# version 2 of the License, or (at your option) any later version.
# Distributions of rdiff-backup should include a copy of the GPL in a
# file called COPYING.  The GPL is also available online at
# https://www.gnu.org/copyleft/gpl.html.
#
# See https://rdiff-backup.net/ for more information.  Please
# send mail to me or the mailing list if you find bugs or have any
# suggestions.

import sys
import rdiff_backup.Main

try:
    import msvcrt
    import os

    msvcrt.setmode(0, os.O_BINARY)
    msvcrt.setmode(1, os.O_BINARY)
except ImportError:
    pass

# the __no_execute__ flag is used for tests
if __name__ == "__main__" and "__no_execute__" not in globals():
    rdiff_backup.Main.error_check_Main(sys.argv[1:])
