#!/usr/bin/env python
# rdiff-backup -- Mirror files while keeping incremental changes
# Version $version released September 16, 2002
# Copyright (C) 2001, 2002 Ben Escoto <bescoto@stanford.edu>
#
# This program is licensed under the GNU General Public License (GPL).
# you can redistribute it and/or modify it under the terms of the GNU
# General Public License as published by the Free Software Foundation,
# Inc., 675 Mass Ave, Cambridge MA 02139, USA; either version 2 of the
# License, or (at your option) any later version.  Distributions of
# rdiff-backup should include a copy of the GPL in a file called
# COPYING.  The GPL is also available online at
# http://www.gnu.org/copyleft/gpl.html.
#
# See http://rdiff-backup.stanford.edu/ for more information.  Please
# send mail to me or the mailing list if you find bugs or have any
# suggestions.

import sys
import rdiff_backup.Main

if __name__ == "__main__" and not globals().has_key('__no_execute__'):
	rdiff_backup.Main.Main(sys.argv[1:])


