---
name: Build-Windows

on:
  push:
    branches: ['*_']
    tags: ['*_']
    paths-ignore: ['docs/**']
  pull_request:
#    branches: [ $default-branch ]
    paths-ignore: ['docs/**']

env:
  PYTHON_VERSION: 3.9.1
  LIBRSYNC_VERSION: v2.2.1

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86, x64]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.1
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
        architecture: ${{ matrix.arch }}
    - name: Install dependencies
      run: |
        tools/win_provision.sh ${PYTHON_VERSION}
    - name: Build librsync
      run: |
        tools/win_build_librsync.sh ${{ matrix.arch }} ${LIBRSYNC_VERSION}
    - name: Build rdiff-backup
      run: |
        tools/win_build_rdiffbackup.sh ${{ matrix.arch }} ${PYTHON_VERSION}
        tools/win_package_rdiffbackup.sh ${{ matrix.arch }}
